In [1]:
import pandas as pd

In [2]:
json = "https://data.cdc.gov/resource/n8mc-b4w4.json?$limit=10000000"
df = pd.read_json(json)
df.head(10)

,case_month,res_state,state_fips_code,res_county,county_fips_code,age_group,sex,race,ethnicity,process,exposure_yn,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn,case_onset_interval,case_positive_specimen
0,2022-06,CA,06,LOS ANGELES,06037,18 to 49 years,Female,Asian,Non-Hispanic/Latino,Missing,Missing,Laboratory-confirmed case,Unknown,No,Missing,Missing,Yes,NaN,NaN
1,2020-12,TX,48,NA,NA,65+ years,NA,NA,NA,Missing,Missing,Laboratory-confirmed case,Symptomatic,Yes,Missing,Yes,NaN,-1.0,NaN
2,2021-12,CA,06,LOS ANGELES,06037,18 to 49 years,Female,Black,Non-Hispanic/Latino,Missing,Missing,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN,NaN,NaN
3,2021-11,NE,31,NA,NA,18 to 49 years,Female,White,Non-Hispanic/Latino,Missing,Missing,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN,0.0,NaN
4,2020-09,TX,48,NA,NA,0 - 17 years,Male,White,Hispanic/Latino,Missing,Missing,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN,-1.0,NaN
5,2022-06,CA,06,LOS ANGELES,06037,18 to 49 years,Female,Asian,Non-Hispanic/Latino,Missing,Missing,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN,0.0,NaN
6,2021-12,CA,06,LOS ANGELES,06037,18 to 49 years,Female,Black,Non-Hispanic/Latino,Missing,Missing,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN,0.0,NaN
7,2021-11,NE,31,NA,NA,18 to 49 years,Female,White,Non-Hispanic/Latino,Missing,Missing,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN,0.0,NaN
8,2022-06,CA,06,LOS ANGELES,06037,18 to 49 years,Female,Asian,Non-Hispanic/Latino,Missing,Missing,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN,NaN,NaN
9,2020-12,TX,48,NA,NA,65+ years,NA,NA,NA,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN,NaN,NaN

In [3]:
df = df.drop(['state_fips_code', 'county_fips_code', 'ethnicity', 'process', 'exposure_yn', 'case_onset_interval', 'case_positive_specimen', 'exposure_yn', 'case_onset_interval', 'case_positive_specimen'], axis=1)
df.head(10)

,case_month,res_state,res_county,age_group,sex,race,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-06,CA,LOS ANGELES,18 to 49 years,Female,Asian,Laboratory-confirmed case,Unknown,No,Missing,Missing,Yes
1,2020-12,TX,NA,65+ years,NA,NA,Laboratory-confirmed case,Symptomatic,Yes,Missing,Yes,NaN
2,2021-12,CA,LOS ANGELES,18 to 49 years,Female,Black,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
3,2021-11,NE,NA,18 to 49 years,Female,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
4,2020-09,TX,NA,0 - 17 years,Male,White,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
5,2022-06,CA,LOS ANGELES,18 to 49 years,Female,Asian,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
6,2021-12,CA,LOS ANGELES,18 to 49 years,Female,Black,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
7,2021-11,NE,NA,18 to 49 years,Female,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
8,2022-06,CA,LOS ANGELES,18 to 49 years,Female,Asian,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
9,2020-12,TX,NA,65+ years,NA,NA,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN

In [8]:
# NA's are populating in case_month with latest JSON query?
df = df[df['case_month'] != 'NA']
df["case_month"].unique()

array(['2022-06', '2020-12', '2021-12', '2021-11', '2020-09', '2022-04',
       '2022-01', '2022-02', '2023-03', '2021-01', '2021-09', '2023-01',
       '2020-10', '2022-10', '2020-11', '2022-07', '2022-08', '2020-04',
       '2020-06', '2021-02', '2022-09', '2022-12', '2022-11', '2021-10',
       '2020-07', '2023-02', '2021-08', '2022-05', '2020-05', '2021-06',
       '2020-03', '2022-03', '2021-04', '2021-05', '2021-03', '2021-07',
       '2020-08', '2020-01', '2020-02'], dtype=object)

In [9]:
df["case_month"] = pd.to_datetime(df["case_month"], format='%Y-%m')
df.dtypes

case_month                  datetime64[ns]
res_state                           object
res_county                          object
age_group                           object
sex                                 object
race                                object
current_status                      object
symptom_status                      object
hosp_yn                             object
icu_yn                              object
death_yn                            object
underlying_conditions_yn            object
dtype: object

In [10]:
len(df)

9999975

In [11]:
# What rows needed to be dropped through dropna()
print(f"Age Group column contains: {df['age_group'].unique()}")
print(f"Sex column contains: {df['sex'].unique()}")
print(f"Race column contains: {df['race'].unique()}")

Age Group column contains: ['18 to 49 years' '65+ years' '0 - 17 years' 'Missing' 'NA'
 '50 to 64 years']
Sex column contains: ['Female' 'NA' 'Male' 'Other' 'Unknown' 'Missing']
Race column contains: ['Asian' 'NA' 'Black' 'White' 'Unknown' 'American Indian/Alaska Native'
 'Missing' 'Native Hawaiian/Other Pacific Islander' 'Multiple/Other']

In [12]:
df.head(10)

,case_month,res_state,res_county,age_group,sex,race,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-06-01,CA,LOS ANGELES,18 to 49 years,Female,Asian,Laboratory-confirmed case,Unknown,No,Missing,Missing,Yes
1,2020-12-01,TX,NA,65+ years,NA,NA,Laboratory-confirmed case,Symptomatic,Yes,Missing,Yes,NaN
2,2021-12-01,CA,LOS ANGELES,18 to 49 years,Female,Black,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
3,2021-11-01,NE,NA,18 to 49 years,Female,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
4,2020-09-01,TX,NA,0 - 17 years,Male,White,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
5,2022-06-01,CA,LOS ANGELES,18 to 49 years,Female,Asian,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
6,2021-12-01,CA,LOS ANGELES,18 to 49 years,Female,Black,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
7,2021-11-01,NE,NA,18 to 49 years,Female,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
8,2022-06-01,CA,LOS ANGELES,18 to 49 years,Female,Asian,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
9,2020-12-01,TX,NA,65+ years,NA,NA,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN

In [13]:
age_df = df.copy()
age_df = age_df.drop(['sex', 'race'], axis=1)
age_df.head()

,case_month,res_state,res_county,age_group,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-06-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Unknown,No,Missing,Missing,Yes
1,2020-12-01,TX,NA,65+ years,Laboratory-confirmed case,Symptomatic,Yes,Missing,Yes,NaN
2,2021-12-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
3,2021-11-01,NE,NA,18 to 49 years,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
4,2020-09-01,TX,NA,0 - 17 years,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN

In [14]:
sex_df = df.copy()
sex_df = sex_df.drop(['age_group', 'race'], axis=1)
sex_df.head()

,case_month,res_state,res_county,sex,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-06-01,CA,LOS ANGELES,Female,Laboratory-confirmed case,Unknown,No,Missing,Missing,Yes
1,2020-12-01,TX,NA,NA,Laboratory-confirmed case,Symptomatic,Yes,Missing,Yes,NaN
2,2021-12-01,CA,LOS ANGELES,Female,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
3,2021-11-01,NE,NA,Female,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
4,2020-09-01,TX,NA,Male,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN

In [15]:
race_df = df.copy()
race_df = race_df.drop(['age_group', 'sex'], axis=1)
race_df.head()

,case_month,res_state,res_county,race,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-06-01,CA,LOS ANGELES,Asian,Laboratory-confirmed case,Unknown,No,Missing,Missing,Yes
1,2020-12-01,TX,NA,NA,Laboratory-confirmed case,Symptomatic,Yes,Missing,Yes,NaN
2,2021-12-01,CA,LOS ANGELES,Black,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
3,2021-11-01,NE,NA,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
4,2020-09-01,TX,NA,White,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN

In [16]:
age_df['age_group'].replace('Missing', pd.NA, inplace=True)
age_df.dropna(subset=['age_group'], inplace = True)
age_df = age_df[age_df['age_group'] != 'NA']
age_df.head(20)

,case_month,res_state,res_county,age_group,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-06-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Unknown,No,Missing,Missing,Yes
1,2020-12-01,TX,NA,65+ years,Laboratory-confirmed case,Symptomatic,Yes,Missing,Yes,NaN
2,2021-12-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
3,2021-11-01,NE,NA,18 to 49 years,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
4,2020-09-01,TX,NA,0 - 17 years,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
5,2022-06-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
6,2021-12-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
7,2021-11-01,NE,NA,18 to 49 years,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
8,2022-06-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
9,2020-12-01,TX,NA,65+ years,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
10,2021-12-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
11,2021-11-01,NE,NA,18 to 49 years,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
12,2020-09-01,TX,NA,0 - 17 years,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
13,2022-06-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
14,2021-12-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
15,2021-11-01,NE,NA,18 to 49 years,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
16,2020-12-01,TX,NA,65+ years,Laboratory-confirmed case,Symptomatic,Yes,Missing,No,NaN
17,2022-06-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
18,2021-12-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
19,2021-11-01,NE,NA,18 to 49 years,Probable Case,Symptomatic,Missing,Missing,Missing,NaN

In [17]:
print(f"Age Group column contains: {age_df['age_group'].unique()}")
print(f"Length of age_df: {len(age_df)}")

Age Group column contains: ['18 to 49 years' '65+ years' '0 - 17 years' '50 to 64 years']
Length of age_df: 9615921

In [18]:
sex_df['sex'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
sex_df = sex_df[sex_df['sex'] != 'NA']
sex_df.dropna(subset=['sex'], inplace = True)
sex_df.head(20)

,case_month,res_state,res_county,sex,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-06-01,CA,LOS ANGELES,Female,Laboratory-confirmed case,Unknown,No,Missing,Missing,Yes
2,2021-12-01,CA,LOS ANGELES,Female,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
3,2021-11-01,NE,NA,Female,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
4,2020-09-01,TX,NA,Male,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
5,2022-06-01,CA,LOS ANGELES,Female,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
6,2021-12-01,CA,LOS ANGELES,Female,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
7,2021-11-01,NE,NA,Female,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
8,2022-06-01,CA,LOS ANGELES,Female,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
10,2021-12-01,CA,LOS ANGELES,Female,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
11,2021-11-01,NE,NA,Female,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
12,2020-09-01,TX,NA,Male,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
13,2022-06-01,CA,LOS ANGELES,Female,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
14,2021-12-01,CA,LOS ANGELES,Female,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
15,2021-11-01,NE,NA,Female,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
17,2022-06-01,CA,LOS ANGELES,Female,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
18,2021-12-01,CA,LOS ANGELES,Female,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
19,2021-11-01,NE,NA,Female,Probable Case,Symptomatic,Missing,Missing,Missing,NaN
20,2020-09-01,TX,NA,Male,Laboratory-confirmed case,Symptomatic,No,Missing,No,NaN
21,2022-06-01,CA,LOS ANGELES,Female,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
22,2021-12-01,CA,LOS ANGELES,Female,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN

In [19]:
print(f"Sex column contains: {sex_df['sex'].unique()}")
print(f"Length of sex_df: {len(sex_df)}")

Sex column contains: ['Female' 'Male' 'Other']
Length of sex_df: 8969565

In [20]:
race_df['race'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
race_df = race_df[race_df['race'] != 'NA']
race_df.dropna(subset=['race'], inplace = True)
race_df.head(20)

,case_month,res_state,res_county,race,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-06-01,CA,LOS ANGELES,Asian,Laboratory-confirmed case,Unknown,No,Missing,Missing,Yes
2,2021-12-01,CA,LOS ANGELES,Black,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
3,2021-11-01,NE,NA,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
4,2020-09-01,TX,NA,White,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
5,2022-06-01,CA,LOS ANGELES,Asian,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
6,2021-12-01,CA,LOS ANGELES,Black,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
7,2021-11-01,NE,NA,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
8,2022-06-01,CA,LOS ANGELES,Asian,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
10,2021-12-01,CA,LOS ANGELES,Black,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
11,2021-11-01,NE,NA,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
12,2020-09-01,TX,NA,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
13,2022-06-01,CA,LOS ANGELES,Asian,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
14,2021-12-01,CA,LOS ANGELES,Black,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
15,2021-11-01,NE,NA,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
17,2022-06-01,CA,LOS ANGELES,Asian,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
18,2021-12-01,CA,LOS ANGELES,Black,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
19,2021-11-01,NE,NA,White,Probable Case,Symptomatic,Missing,Missing,Missing,NaN
20,2020-09-01,TX,NA,White,Laboratory-confirmed case,Symptomatic,No,Missing,No,NaN
21,2022-06-01,CA,LOS ANGELES,Asian,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
22,2021-12-01,CA,LOS ANGELES,Black,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN

In [21]:
print(f"Race column contains: {race_df['race'].unique()}")
print(f"Length of race_df: {len(race_df)}")

Race column contains: ['Asian' 'Black' 'White' 'American Indian/Alaska Native'
 'Native Hawaiian/Other Pacific Islander' 'Multiple/Other']
Length of race_df: 6065484

In [22]:
age_df.to_csv('resources/demographic_analysis/age.csv', index = False)

KeyboardInterrupt:

In [ ]:
sex_df.to_csv('resources/demographic_analysis/sex.csv', index = False)

In [ ]:
race_df.to_csv('resources/demographic_analysis/race.csv', index = False)

In [23]:
count = (age_df[(age_df['age_group'] == '18 to 49 years') & (age_df['death_yn'] == 'Yes')])
count.head()

,case_month,res_state,res_county,age_group,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
375563,2022-01-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Unknown,Yes,Unknown,Yes,NaN
376654,2022-01-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Unknown,No,Missing,Yes,NaN
376666,2022-01-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Unknown,Yes,Yes,Yes,NaN
378430,2022-01-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Unknown,Yes,Unknown,Yes,NaN
378570,2022-01-01,CA,LOS ANGELES,18 to 49 years,Laboratory-confirmed case,Symptomatic,Yes,Unknown,Yes,NaN

In [24]:
len(count)

889

In [25]:
len(age_df)

9615921

In [26]:
age_df_subset = age_df.head(1000000)
sex_df_subset = sex_df.head(1000000)
race_df_subset = race_df.head(1000000)

age_df_subset.to_csv('resources/demographic_analysis/sample_age.csv', index = False)
sex_df_subset.to_csv('resources/demographic_analysis/sample_sex.csv', index = False)
race_df_subset.to_csv('resources/demographic_analysis/sample_race.csv', index = False)

KeyboardInterrupt:

# All three datasets for Tableau

In [27]:
tableau_df = df.copy()
tableau_df['age_group'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
tableau_df['sex'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
tableau_df['race'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
tableau_df.head()

,case_month,res_state,res_county,age_group,sex,race,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-06-01,CA,LOS ANGELES,18 to 49 years,Female,Asian,Laboratory-confirmed case,Unknown,No,Missing,Missing,Yes
1,2020-12-01,TX,NA,65+ years,NA,NA,Laboratory-confirmed case,Symptomatic,Yes,Missing,Yes,NaN
2,2021-12-01,CA,LOS ANGELES,18 to 49 years,Female,Black,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
3,2021-11-01,NE,NA,18 to 49 years,Female,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
4,2020-09-01,TX,NA,0 - 17 years,Male,White,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN

In [28]:
tableau_df.dropna(subset=['age_group', 'sex', 'race'], inplace = True)

display(tableau_df.head(10))
print(len(tableau_df))

,case_month,res_state,res_county,age_group,sex,race,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-06-01,CA,LOS ANGELES,18 to 49 years,Female,Asian,Laboratory-confirmed case,Unknown,No,Missing,Missing,Yes
1,2020-12-01,TX,NA,65+ years,NA,NA,Laboratory-confirmed case,Symptomatic,Yes,Missing,Yes,NaN
2,2021-12-01,CA,LOS ANGELES,18 to 49 years,Female,Black,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
3,2021-11-01,NE,NA,18 to 49 years,Female,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
4,2020-09-01,TX,NA,0 - 17 years,Male,White,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
5,2022-06-01,CA,LOS ANGELES,18 to 49 years,Female,Asian,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
6,2021-12-01,CA,LOS ANGELES,18 to 49 years,Female,Black,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN
7,2021-11-01,NE,NA,18 to 49 years,Female,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
8,2022-06-01,CA,LOS ANGELES,18 to 49 years,Female,Asian,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN
9,2020-12-01,TX,NA,65+ years,NA,NA,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN

7763759

In [ ]:
import numpy as np

tableau_df[['age_group', 'sex', 'race']] = tableau_df[['age_group', 'sex', 'race']].replace('NA', np.nan)

In [ ]:
tableau_df.dropna(subset=['age_group', 'sex', 'race'], inplace = True)

In [ ]:
tableau_columns = ['age_group', 'sex', 'race']
for col in tableau_columns: 
    print(col, tableau_df[col].unique())

age_group ['50 to 64 years' '18 to 49 years' '65+ years' '0 - 17 years']
sex ['Female' 'Male' 'Other']
race ['White' 'Black' 'Asian' 'Multiple/Other' 'American Indian/Alaska Native'
 'Native Hawaiian/Other Pacific Islander']

In [ ]:
display(tableau_df.head(10))
print(len(tableau_df))

,case_month,res_state,res_county,age_group,sex,race,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-11-01,HI,HONOLULU,50 to 64 years,Female,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
2,2021-08-01,ID,ADA,18 to 49 years,Male,White,Laboratory-confirmed case,Unknown,No,Missing,No,NaN
6,2021-01-01,SC,SPARTANBURG,18 to 49 years,Female,Black,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
7,2022-05-01,MD,ANNE ARUNDEL,18 to 49 years,Male,White,Probable Case,Symptomatic,Missing,Missing,No,NaN
8,2022-03-01,FL,MIAMI-DADE,50 to 64 years,Male,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
10,2022-05-01,NJ,UNION,50 to 64 years,Male,Asian,Laboratory-confirmed case,Symptomatic,Yes,Missing,No,NaN
11,2023-02-01,MI,INGHAM,18 to 49 years,Female,Black,Laboratory-confirmed case,Missing,Missing,Missing,Unknown,NaN
12,2022-07-01,FL,ST. LUCIE,18 to 49 years,Female,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
13,2022-01-01,MN,DAKOTA,50 to 64 years,Female,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,No,Yes
14,2021-10-01,MI,KALAMAZOO,18 to 49 years,Male,White,Probable Case,Missing,Missing,Missing,Unknown,NaN

6389751

In [ ]:
tableau_df.to_csv('resources/demographic_analysis/tableau.csv', index = False)

# Cleaned DataFrame for Machine Learning

In [29]:
clean_df = df.copy()
clean_df = clean_df.drop(['case_month', 'res_state', 'res_county', 'hosp_yn'], axis=1)
clean_df.head(10)

,age_group,sex,race,current_status,symptom_status,icu_yn,death_yn,underlying_conditions_yn
0,18 to 49 years,Female,Asian,Laboratory-confirmed case,Unknown,Missing,Missing,Yes
1,65+ years,NA,NA,Laboratory-confirmed case,Symptomatic,Missing,Yes,NaN
2,18 to 49 years,Female,Black,Laboratory-confirmed case,Unknown,Missing,Missing,NaN
3,18 to 49 years,Female,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,NaN
4,0 - 17 years,Male,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,NaN
5,18 to 49 years,Female,Asian,Laboratory-confirmed case,Symptomatic,Missing,Missing,NaN
6,18 to 49 years,Female,Black,Laboratory-confirmed case,Symptomatic,Missing,Missing,NaN
7,18 to 49 years,Female,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,NaN
8,18 to 49 years,Female,Asian,Laboratory-confirmed case,Unknown,Missing,Missing,NaN
9,65+ years,NA,NA,Laboratory-confirmed case,Missing,Missing,Missing,NaN

In [30]:
for col in clean_df.columns: 
    print(col, df[col].unique())

age_group ['18 to 49 years' '65+ years' '0 - 17 years' 'Missing' 'NA'
 '50 to 64 years']
sex ['Female' 'NA' 'Male' 'Other' 'Unknown' 'Missing']
race ['Asian' 'NA' 'Black' 'White' 'Unknown' 'American Indian/Alaska Native'
 'Missing' 'Native Hawaiian/Other Pacific Islander' 'Multiple/Other']
current_status ['Laboratory-confirmed case' 'Probable Case']
symptom_status ['Unknown' 'Symptomatic' 'Missing' 'Asymptomatic']
icu_yn ['Missing' 'No' 'Unknown' 'Yes']
death_yn ['Missing' 'Yes' 'No' 'NA' 'Unknown']
underlying_conditions_yn ['Yes' nan 'No']

In [31]:
clean_df['age_group'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
clean_df['sex'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
clean_df['race'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
clean_df['symptom_status'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
clean_df['icu_yn'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
clean_df['death_yn'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)

clean_df = clean_df[clean_df[['age_group', 'sex', 'race', 'symptom_status', 'icu_yn', 'death_yn']] != 'NA']
clean_df.dropna(subset=['age_group', 'sex', 'race', 'symptom_status', 'icu_yn', 'death_yn'], inplace = True)
clean_df.head()

,age_group,sex,race,current_status,symptom_status,icu_yn,death_yn,underlying_conditions_yn
8111,18 to 49 years,Female,White,NaN,Symptomatic,No,No,NaN
20608,65+ years,Female,Asian,NaN,Symptomatic,Yes,Yes,NaN
20644,65+ years,Female,Asian,NaN,Symptomatic,Yes,Yes,NaN
20876,65+ years,Female,Asian,NaN,Symptomatic,Yes,Yes,NaN
20912,65+ years,Female,Asian,NaN,Symptomatic,Yes,Yes,NaN

In [32]:
for col in clean_df.columns: 
    print(col, clean_df[col].unique())

age_group ['18 to 49 years' '65+ years' '50 to 64 years' '0 - 17 years']
sex ['Female' 'Male']
race ['White' 'Asian' 'Black' 'American Indian/Alaska Native' 'Multiple/Other'
 'Native Hawaiian/Other Pacific Islander']
current_status [nan]
symptom_status ['Symptomatic' 'Asymptomatic']
icu_yn ['No' 'Yes']
death_yn ['No' 'Yes']
underlying_conditions_yn [nan]

In [33]:
new_clean_df = clean_df.drop(['current_status', 'underlying_conditions_yn'], axis=1)
new_clean_df['death_yn'] = new_clean_df['death_yn'].replace({'Yes': 1, 'No': 0})
new_clean_df.head()

            age_group     sex   race symptom_status icu_yn  death_yn
8111   18 to 49 years  Female  White    Symptomatic     No         0
20608       65+ years  Female  Asian    Symptomatic    Yes         1
20644       65+ years  Female  Asian    Symptomatic    Yes         1
20876       65+ years  Female  Asian    Symptomatic    Yes         1
20912       65+ years  Female  Asian    Symptomatic    Yes         1

In [34]:
new_clean_df.dtypes

age_group         object
sex               object
race              object
symptom_status    object
icu_yn            object
death_yn           int64
dtype: object

In [35]:
encoded_df = pd.get_dummies(new_clean_df, columns = ['age_group', 'sex', 'race', 'symptom_status', 'icu_yn'])
encoded_df.head(25)

,death_yn,age_group_0 - 17 years,age_group_18 to 49 years,age_group_50 to 64 years,age_group_65+ years,sex_Female,sex_Male,race_American Indian/Alaska Native,race_Asian,race_Black,race_Multiple/Other,race_Native Hawaiian/Other Pacific Islander,race_White,symptom_status_Asymptomatic,symptom_status_Symptomatic,icu_yn_No,icu_yn_Yes
8111,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
20608,1,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,1
20644,1,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,1
20876,1,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,1
20912,1,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,1
20916,1,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,1
21032,1,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,1
21044,1,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,1
21056,1,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,1
21164,1,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,1
21304,1,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,1
31087,1,0,0,0,1,0,1,0,0,0,0,0,1,0,1,1,0
31090,0,0,0,0,1,0,1,0,0,0,0,0,1,0,1,1,0
31115,1,0,0,0,1,0,1,0,0,0,0,0,1,0,1,1,0
31119,1,0,0,0,1,0,1,0,0,0,0,0,1,0,1,1,0
31127,1,0,0,0,1,0,1,0,0,0,0,0,1,0,1,1,0
31507,1,0,0,0,1,0,1,0,0,0,0,0,1,0,1,1,0
31555,1,0,0,0,1,0,1,0,0,0,0,0,1,0,1,0,1
31678,0,0,0,0,1,0,1,0,0,0,0,0,1,0,1,1,0
31867,1,0,0,0,1,0,1,0,0,0,0,0,1,0,1,0,1
32002,0,0,0,0,1,0,1,0,0,0,0,0,1,0,1,1,0
32439,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0,1,0
41380,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1,1,0
46428,1,0,0,0,1,1,0,0,0,1,0,0,0,0,1,0,1
46464,1,0,0,0,1,1,0,0,0,1,0,0,0,0,1,0,1

In [36]:
encoded_df['death_yn'].unique()

array([0, 1], dtype=int64)

In [37]:
# Set up for machine learning mortality model
y = encoded_df['death_yn']
X = encoded_df.drop(columns= 'death_yn')

# Logistic Regression Attempt

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=1, stratify=y)

In [39]:
# Initiate similar to Module #18

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
   max_iter=10000,
   random_state=1)

In [40]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=10000, random_state=1)

In [41]:
y_pred = classifier.predict(X_test)

In [42]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(f"Accuracy Score: {accuracy_score(y_test, y_pred)}")
print("\nClassification Report: \n")
report = classification_report(y_test, y_pred)
print(report)

Accuracy Score: 0.9742631520409298

Classification Report:

              precision    recall  f1-score   support

           0       0.98      0.99      0.99     43345
           1       0.68      0.53      0.59      1610

    accuracy                           0.97     44955
   macro avg       0.83      0.76      0.79     44955
weighted avg       0.97      0.97      0.97     44955

In [43]:
cm_log = confusion_matrix(y_test, y_pred)
cm_log_df = pd.DataFrame(
    cm_log, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_log_df

          Predicted 0  Predicted 1
Actual 0        42949          396
Actual 1          761          849

# SVC

In [44]:
X_train_SVC, X_test_SVC, y_train_SVC, y_test_SVC = train_test_split(X,
   y,  random_state=1, stratify=y)
X_train_SVC.shape

(134864, 16)

In [45]:
from sklearn.svm import SVC
model = SVC(kernel='linear')

In [46]:
model.fit(X_train_SVC, y_train_SVC)

SVC(kernel='linear')

In [47]:
y_pred_SVC = model.predict(X_test_SVC)

In [48]:
cm_SVC = confusion_matrix(y_test_SVC, y_pred_SVC)
cm_SVC_df = pd.DataFrame(
    cm_SVC, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_SVC_df

          Predicted 0  Predicted 1
Actual 0        42940          405
Actual 1          755          855

In [49]:
print(f"Accuracy Score: {accuracy_score(y_test_SVC, y_pred_SVC)}")
print(classification_report(y_test_SVC, y_pred_SVC))

Accuracy Score: 0.974196418640863
              precision    recall  f1-score   support

           0       0.98      0.99      0.99     43345
           1       0.68      0.53      0.60      1610

    accuracy                           0.97     44955
   macro avg       0.83      0.76      0.79     44955
weighted avg       0.97      0.97      0.97     44955

# Random Forest

In [50]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

In [51]:
X_train_RF, X_test_RF, y_train_RF, y_test_RF = train_test_split(X, y, random_state=1)

In [52]:
scaler = StandardScaler()
X_scaler = scaler.fit(X_train_RF)

X_train_scaled_RF = X_scaler.transform(X_train_RF)
X_test_scaled_RF = X_scaler.transform(X_test_RF)

In [53]:
rf_model = RandomForestClassifier(n_estimators=128, random_state=1) 
rf_model = rf_model.fit(X_train_scaled_RF, y_train_RF)

In [54]:
predictions_RF = rf_model.predict(X_test_scaled_RF)
cm = confusion_matrix(y_test_RF, predictions_RF)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

In [55]:
acc_score_RF = accuracy_score(y_test_RF, predictions_RF)

In [56]:
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score_RF}")
print("Classification Report")
print(classification_report(y_test_RF, predictions_RF))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0        42763          590
Actual 1          576         1026

Accuracy Score : 0.9740629518407297
Classification Report
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     43353
           1       0.63      0.64      0.64      1602

    accuracy                           0.97     44955
   macro avg       0.81      0.81      0.81     44955
weighted avg       0.97      0.97      0.97     44955

# Random Oversampler

In [57]:
from collections import Counter
X_train_ROS, X_test_ROS, y_train_ROS, y_test_ROS = train_test_split(X, y, random_state=1)
Counter(y_train)

Counter({0: 130036, 1: 4828})

In [58]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)

X_resampled_ROS, y_resampled_ROS = ros.fit_resample(X_train_ROS, y_train_ROS)

In [59]:
model_ROS = LogisticRegression(solver='lbfgs', max_iter=500, random_state=1)
model_ROS.fit(X_resampled_ROS, y_resampled_ROS)

LogisticRegression(max_iter=500, random_state=1)

In [60]:
y_pred_ROS = model.predict(X_test_ROS)

cm_ROS = confusion_matrix(y_test_ROS, y_pred_ROS)
cm_df_ROS = pd.DataFrame(
    cm_ROS, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

In [61]:
from imblearn.metrics import classification_report_imbalanced
from sklearn.metrics import balanced_accuracy_score

acc_score_ROS= balanced_accuracy_score(y_test_RF, y_pred_ROS)

print("Confusion Matrix")
display(cm_df_ROS)
print(f"Accuracy Score : {acc_score_ROS}")
print("Classification Report")
print(classification_report_imbalanced(y_test_RF, y_pred_ROS))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0        42906          447
Actual 1          735          867

Accuracy Score : 0.7654438983655732
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

          0       0.98      0.99      0.54      0.99      0.73      0.56     43353
          1       0.66      0.54      0.99      0.59      0.73      0.51      1602

avg / total       0.97      0.97      0.56      0.97      0.73      0.56     44955

# SMOTEENN

In [62]:
X_train_SMOTEENN, X_test_SMOTEENN, y_train_SMOTEENN, y_test_SMOTEENN = train_test_split(X, y, random_state=1)

In [72]:
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=1)
X_resampled_SMOTEENN, y_resampled_SMOTEENN = smote_enn.fit_resample(X, y)

KeyboardInterrupt:

In [ ]:
model_SMOTEENN = LogisticRegression(solver='lbfgs', random_state=1)
model_SMOTEENN.fit(X_resampled_SMOTEENN, y_resampled_SMOTEENN)

In [ ]:
y_pred_SMOTEENN = model_SMOTEENN.predict(X_test)
cm_SMOTEENN = confusion_matrix(y_test_ROS, y_pred_ROS)
cm_df_SMOTEENN = pd.DataFrame(
    cm_SMOTEENN, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

In [ ]:
acc_score_SMOTEENN = balanced_accuracy_score(y_test_SMOTEENN, y_pred_SMOTEENN)

print("Confusion Matrix")
display(cm_df_SMOTEENN)
print(f"Accuracy Score : {acc_score_SMOTEENN}")
print("Classification Report")
print(classification_report_imbalanced(y_test_SMOTEENN, y_pred_SMOTEENN))