In [13]:
import pandas as pd

In [14]:
json = "https://data.cdc.gov/resource/n8mc-b4w4.json?$limit=10000000"
df = pd.read_json(json)
df.head(10)

,case_month,res_state,state_fips_code,res_county,county_fips_code,age_group,sex,race,ethnicity,process,exposure_yn,current_status,symptom_status,hosp_yn,icu_yn,death_yn,case_positive_specimen,case_onset_interval,underlying_conditions_yn
0,2022-11,HI,15,HONOLULU,15003,50 to 64 years,Female,White,Unknown,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN,NaN,NaN
1,2021-07,FL,12,PALM BEACH,12099,18 to 49 years,Female,Unknown,Hispanic/Latino,Missing,Missing,Laboratory-confirmed case,Symptomatic,No,Missing,No,0.0,0.0,NaN
2,2021-08,ID,16,ADA,16001,18 to 49 years,Male,White,Non-Hispanic/Latino,Missing,Missing,Laboratory-confirmed case,Unknown,No,Missing,No,0.0,NaN,NaN
3,2022-01,CA,6,ORANGE,06059,0 - 17 years,Female,Unknown,Unknown,Missing,Missing,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN,NaN,NaN
4,2021-08,OH,39,LORAIN,39093,0 - 17 years,Male,Unknown,Unknown,Missing,Missing,Probable Case,Missing,Missing,Missing,Unknown,0.0,NaN,NaN
5,2021-02,MA,25,NORFOLK,25021,50 to 64 years,Male,Unknown,Unknown,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,0.0,NaN,NaN
6,2021-01,SC,45,SPARTANBURG,45083,18 to 49 years,Female,Black,Unknown,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN,NaN,NaN
7,2022-05,MD,24,ANNE ARUNDEL,24003,18 to 49 years,Male,White,Missing,Missing,Missing,Probable Case,Symptomatic,Missing,Missing,No,NaN,0.0,NaN
8,2022-03,FL,12,MIAMI-DADE,12086,50 to 64 years,Male,White,Hispanic/Latino,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN,NaN,NaN
9,2022-08,WI,55,MILWAUKEE,55079,18 to 49 years,Female,Unknown,Non-Hispanic/Latino,Missing,Missing,Probable Case,Missing,Unknown,Missing,Unknown,NaN,NaN,NaN

In [15]:
df = df.drop(['state_fips_code', 'county_fips_code', 'ethnicity', 'process', 'exposure_yn', 'case_onset_interval', 'case_positive_specimen', 'exposure_yn', 'case_onset_interval', 'case_positive_specimen'], axis=1)
df.head(10)

,case_month,res_state,res_county,age_group,sex,race,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-11,HI,HONOLULU,50 to 64 years,Female,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
1,2021-07,FL,PALM BEACH,18 to 49 years,Female,Unknown,Laboratory-confirmed case,Symptomatic,No,Missing,No,NaN
2,2021-08,ID,ADA,18 to 49 years,Male,White,Laboratory-confirmed case,Unknown,No,Missing,No,NaN
3,2022-01,CA,ORANGE,0 - 17 years,Female,Unknown,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN
4,2021-08,OH,LORAIN,0 - 17 years,Male,Unknown,Probable Case,Missing,Missing,Missing,Unknown,NaN
5,2021-02,MA,NORFOLK,50 to 64 years,Male,Unknown,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
6,2021-01,SC,SPARTANBURG,18 to 49 years,Female,Black,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
7,2022-05,MD,ANNE ARUNDEL,18 to 49 years,Male,White,Probable Case,Symptomatic,Missing,Missing,No,NaN
8,2022-03,FL,MIAMI-DADE,50 to 64 years,Male,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
9,2022-08,WI,MILWAUKEE,18 to 49 years,Female,Unknown,Probable Case,Missing,Unknown,Missing,Unknown,NaN

In [16]:
df["case_month"] = pd.to_datetime(df["case_month"], format='%Y-%m')
df.dtypes

case_month                  datetime64[ns]
res_state                           object
res_county                          object
age_group                           object
sex                                 object
race                                object
current_status                      object
symptom_status                      object
hosp_yn                             object
icu_yn                              object
death_yn                            object
underlying_conditions_yn            object
dtype: object

In [17]:
len(df)

10000000

In [18]:
# What rows needed to be dropped through dropna()
print(f"Age Group column contains: {df['age_group'].unique()}")
print(f"Sex column contains: {df['sex'].unique()}")
print(f"Race column contains: {df['race'].unique()}")

Age Group column contains: ['50 to 64 years' '18 to 49 years' '0 - 17 years' '65+ years' 'Missing'
 'NA']
Sex column contains: ['Female' 'Male' 'Unknown' 'NA' 'Missing' 'Other']
Race column contains: ['White' 'Unknown' 'Black' 'Asian' 'Missing' 'NA' 'Multiple/Other'
 'American Indian/Alaska Native' 'Native Hawaiian/Other Pacific Islander']

In [19]:
df.head(10)

,case_month,res_state,res_county,age_group,sex,race,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-11-01,HI,HONOLULU,50 to 64 years,Female,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
1,2021-07-01,FL,PALM BEACH,18 to 49 years,Female,Unknown,Laboratory-confirmed case,Symptomatic,No,Missing,No,NaN
2,2021-08-01,ID,ADA,18 to 49 years,Male,White,Laboratory-confirmed case,Unknown,No,Missing,No,NaN
3,2022-01-01,CA,ORANGE,0 - 17 years,Female,Unknown,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN
4,2021-08-01,OH,LORAIN,0 - 17 years,Male,Unknown,Probable Case,Missing,Missing,Missing,Unknown,NaN
5,2021-02-01,MA,NORFOLK,50 to 64 years,Male,Unknown,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
6,2021-01-01,SC,SPARTANBURG,18 to 49 years,Female,Black,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
7,2022-05-01,MD,ANNE ARUNDEL,18 to 49 years,Male,White,Probable Case,Symptomatic,Missing,Missing,No,NaN
8,2022-03-01,FL,MIAMI-DADE,50 to 64 years,Male,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
9,2022-08-01,WI,MILWAUKEE,18 to 49 years,Female,Unknown,Probable Case,Missing,Unknown,Missing,Unknown,NaN

In [20]:
age_df = df.copy()
age_df = age_df.drop(['sex', 'race'], axis=1)
age_df.head()

,case_month,res_state,res_county,age_group,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-11-01,HI,HONOLULU,50 to 64 years,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
1,2021-07-01,FL,PALM BEACH,18 to 49 years,Laboratory-confirmed case,Symptomatic,No,Missing,No,NaN
2,2021-08-01,ID,ADA,18 to 49 years,Laboratory-confirmed case,Unknown,No,Missing,No,NaN
3,2022-01-01,CA,ORANGE,0 - 17 years,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN
4,2021-08-01,OH,LORAIN,0 - 17 years,Probable Case,Missing,Missing,Missing,Unknown,NaN

In [21]:
sex_df = df.copy()
sex_df = sex_df.drop(['age_group', 'race'], axis=1)
sex_df.head()

,case_month,res_state,res_county,sex,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-11-01,HI,HONOLULU,Female,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
1,2021-07-01,FL,PALM BEACH,Female,Laboratory-confirmed case,Symptomatic,No,Missing,No,NaN
2,2021-08-01,ID,ADA,Male,Laboratory-confirmed case,Unknown,No,Missing,No,NaN
3,2022-01-01,CA,ORANGE,Female,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN
4,2021-08-01,OH,LORAIN,Male,Probable Case,Missing,Missing,Missing,Unknown,NaN

In [22]:
race_df = df.copy()
race_df = race_df.drop(['age_group', 'sex'], axis=1)
race_df.head()

,case_month,res_state,res_county,race,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-11-01,HI,HONOLULU,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
1,2021-07-01,FL,PALM BEACH,Unknown,Laboratory-confirmed case,Symptomatic,No,Missing,No,NaN
2,2021-08-01,ID,ADA,White,Laboratory-confirmed case,Unknown,No,Missing,No,NaN
3,2022-01-01,CA,ORANGE,Unknown,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN
4,2021-08-01,OH,LORAIN,Unknown,Probable Case,Missing,Missing,Missing,Unknown,NaN

In [23]:
age_df['age_group'].replace('Missing', pd.NA, inplace=True)
age_df.dropna(subset=['age_group'], inplace = True)
age_df = age_df[age_df['age_group'] != 'NA']
age_df.head(20)

,case_month,res_state,res_county,age_group,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-11-01,HI,HONOLULU,50 to 64 years,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
1,2021-07-01,FL,PALM BEACH,18 to 49 years,Laboratory-confirmed case,Symptomatic,No,Missing,No,NaN
2,2021-08-01,ID,ADA,18 to 49 years,Laboratory-confirmed case,Unknown,No,Missing,No,NaN
3,2022-01-01,CA,ORANGE,0 - 17 years,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN
4,2021-08-01,OH,LORAIN,0 - 17 years,Probable Case,Missing,Missing,Missing,Unknown,NaN
5,2021-02-01,MA,NORFOLK,50 to 64 years,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
6,2021-01-01,SC,SPARTANBURG,18 to 49 years,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
7,2022-05-01,MD,ANNE ARUNDEL,18 to 49 years,Probable Case,Symptomatic,Missing,Missing,No,NaN
8,2022-03-01,FL,MIAMI-DADE,50 to 64 years,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
9,2022-08-01,WI,MILWAUKEE,18 to 49 years,Probable Case,Missing,Unknown,Missing,Unknown,NaN
10,2022-05-01,NJ,UNION,50 to 64 years,Laboratory-confirmed case,Symptomatic,Yes,Missing,No,NaN
11,2023-02-01,MI,INGHAM,18 to 49 years,Laboratory-confirmed case,Missing,Missing,Missing,Unknown,NaN
12,2022-07-01,FL,ST. LUCIE,18 to 49 years,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
13,2022-01-01,MN,DAKOTA,50 to 64 years,Laboratory-confirmed case,Symptomatic,Missing,Missing,No,Yes
14,2021-10-01,MI,KALAMAZOO,18 to 49 years,Probable Case,Missing,Missing,Missing,Unknown,NaN
15,2022-06-01,CA,SANTA CRUZ,18 to 49 years,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN
16,2021-06-01,PA,YORK,65+ years,Laboratory-confirmed case,Symptomatic,Unknown,Unknown,Unknown,NaN
17,2021-11-01,PA,DAUPHIN,0 - 17 years,Laboratory-confirmed case,Symptomatic,Unknown,Unknown,Unknown,NaN
18,2022-04-01,SC,HORRY,50 to 64 years,Probable Case,Missing,Missing,Missing,Missing,NaN
19,2020-11-01,KS,SEDGWICK,0 - 17 years,Laboratory-confirmed case,Symptomatic,No,No,No,NaN

In [24]:
print(f"Age Group column contains: {age_df['age_group'].unique()}")
print(f"Length of age_df: {len(age_df)}")

Age Group column contains: ['50 to 64 years' '18 to 49 years' '0 - 17 years' '65+ years']
Length of age_df: 9906005

In [25]:
sex_df['sex'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
sex_df = sex_df[sex_df['sex'] != 'NA']
sex_df.dropna(subset=['sex'], inplace = True)
sex_df.head(20)

,case_month,res_state,res_county,sex,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-11-01,HI,HONOLULU,Female,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
1,2021-07-01,FL,PALM BEACH,Female,Laboratory-confirmed case,Symptomatic,No,Missing,No,NaN
2,2021-08-01,ID,ADA,Male,Laboratory-confirmed case,Unknown,No,Missing,No,NaN
3,2022-01-01,CA,ORANGE,Female,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN
4,2021-08-01,OH,LORAIN,Male,Probable Case,Missing,Missing,Missing,Unknown,NaN
5,2021-02-01,MA,NORFOLK,Male,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
6,2021-01-01,SC,SPARTANBURG,Female,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
7,2022-05-01,MD,ANNE ARUNDEL,Male,Probable Case,Symptomatic,Missing,Missing,No,NaN
8,2022-03-01,FL,MIAMI-DADE,Male,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
9,2022-08-01,WI,MILWAUKEE,Female,Probable Case,Missing,Unknown,Missing,Unknown,NaN
10,2022-05-01,NJ,UNION,Male,Laboratory-confirmed case,Symptomatic,Yes,Missing,No,NaN
11,2023-02-01,MI,INGHAM,Female,Laboratory-confirmed case,Missing,Missing,Missing,Unknown,NaN
12,2022-07-01,FL,ST. LUCIE,Female,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
13,2022-01-01,MN,DAKOTA,Female,Laboratory-confirmed case,Symptomatic,Missing,Missing,No,Yes
14,2021-10-01,MI,KALAMAZOO,Male,Probable Case,Missing,Missing,Missing,Unknown,NaN
15,2022-06-01,CA,SANTA CRUZ,Male,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN
16,2021-06-01,PA,YORK,Male,Laboratory-confirmed case,Symptomatic,Unknown,Unknown,Unknown,NaN
17,2021-11-01,PA,DAUPHIN,Female,Laboratory-confirmed case,Symptomatic,Unknown,Unknown,Unknown,NaN
18,2022-04-01,SC,HORRY,Male,Probable Case,Missing,Missing,Missing,Missing,NaN
19,2020-11-01,KS,SEDGWICK,Male,Laboratory-confirmed case,Symptomatic,No,No,No,NaN

In [26]:
print(f"Sex column contains: {sex_df['sex'].unique()}")
print(f"Length of sex_df: {len(sex_df)}")

Sex column contains: ['Female' 'Male' 'Other']
Length of sex_df: 9782962

In [27]:
race_df['race'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
race_df = race_df[race_df['race'] != 'NA']
race_df.dropna(subset=['race'], inplace = True)
race_df.head(20)

,case_month,res_state,res_county,race,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-11-01,HI,HONOLULU,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
2,2021-08-01,ID,ADA,White,Laboratory-confirmed case,Unknown,No,Missing,No,NaN
6,2021-01-01,SC,SPARTANBURG,Black,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
7,2022-05-01,MD,ANNE ARUNDEL,White,Probable Case,Symptomatic,Missing,Missing,No,NaN
8,2022-03-01,FL,MIAMI-DADE,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
10,2022-05-01,NJ,UNION,Asian,Laboratory-confirmed case,Symptomatic,Yes,Missing,No,NaN
11,2023-02-01,MI,INGHAM,Black,Laboratory-confirmed case,Missing,Missing,Missing,Unknown,NaN
12,2022-07-01,FL,ST. LUCIE,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
13,2022-01-01,MN,DAKOTA,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,No,Yes
14,2021-10-01,MI,KALAMAZOO,White,Probable Case,Missing,Missing,Missing,Unknown,NaN
15,2022-06-01,CA,SANTA CRUZ,White,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN
16,2021-06-01,PA,YORK,White,Laboratory-confirmed case,Symptomatic,Unknown,Unknown,Unknown,NaN
19,2020-11-01,KS,SEDGWICK,Asian,Laboratory-confirmed case,Symptomatic,No,No,No,NaN
20,2020-12-01,NJ,ESSEX,Black,Laboratory-confirmed case,Missing,No,Missing,No,NaN
21,2021-03-01,MD,BALTIMORE CITY,Black,Laboratory-confirmed case,Symptomatic,No,Missing,No,NaN
22,2021-01-01,MI,MACOMB,White,Laboratory-confirmed case,Symptomatic,No,Missing,No,Yes
23,2021-01-01,NY,ONEIDA,White,Laboratory-confirmed case,Symptomatic,No,Missing,No,NaN
24,2021-02-01,FL,PINELLAS,White,Laboratory-confirmed case,Missing,No,Missing,No,NaN
25,2021-10-01,CA,KERN,White,Laboratory-confirmed case,Symptomatic,Yes,No,Missing,NaN
27,2021-07-01,IN,MARION,White,Laboratory-confirmed case,Missing,No,Missing,No,NaN

In [28]:
print(f"Race column contains: {race_df['race'].unique()}")
print(f"Length of race_df: {len(race_df)}")

Race column contains: ['White' 'Black' 'Asian' 'Multiple/Other' 'American Indian/Alaska Native'
 'Native Hawaiian/Other Pacific Islander']
Length of race_df: 6475769

In [29]:
age_df.to_csv('resources/demographic_analysis/age.csv', index = False)

In [30]:
sex_df.to_csv('resources/demographic_analysis/sex.csv', index = False)

In [31]:
race_df.to_csv('resources/demographic_analysis/race.csv', index = False)

In [32]:
count = (age_df[(age_df['age_group'] == '18 to 49 years') & (age_df['death_yn'] == 'Yes')])
count.head()

,case_month,res_state,res_county,age_group,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
80414,2021-08-01,AL,JEFFERSON,18 to 49 years,Laboratory-confirmed case,Missing,Yes,Missing,Yes,NaN
94020,2021-08-01,AL,JEFFERSON,18 to 49 years,Laboratory-confirmed case,Missing,Yes,Missing,Yes,NaN
97008,2021-08-01,AL,JEFFERSON,18 to 49 years,Laboratory-confirmed case,Missing,Missing,Missing,Yes,NaN
97283,2021-08-01,AL,JEFFERSON,18 to 49 years,Probable Case,Missing,Unknown,Missing,Yes,NaN
97376,2021-08-01,FL,POLK,18 to 49 years,Laboratory-confirmed case,Missing,Yes,Missing,Yes,NaN

In [33]:
len(count)

406

In [34]:
len(age_df)

9906005

In [35]:
age_df_subset = age_df.head(1000000)
sex_df_subset = sex_df.head(1000000)
race_df_subset = race_df.head(1000000)

age_df_subset.to_csv('resources/demographic_analysis/sample_age.csv', index = False)
sex_df_subset.to_csv('resources/demographic_analysis/sample_sex.csv', index = False)
race_df_subset.to_csv('resources/demographic_analysis/sample_race.csv', index = False)

# All three datasets for Tableau

In [156]:
tableau_df = df.copy()
tableau_df['age_group'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
tableau_df['sex'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
tableau_df['race'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
tableau_df.head()

,case_month,res_state,res_county,age_group,sex,race,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-11-01,HI,HONOLULU,50 to 64 years,Female,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
1,2021-07-01,FL,PALM BEACH,18 to 49 years,Female,<NA>,Laboratory-confirmed case,Symptomatic,No,Missing,No,NaN
2,2021-08-01,ID,ADA,18 to 49 years,Male,White,Laboratory-confirmed case,Unknown,No,Missing,No,NaN
3,2022-01-01,CA,ORANGE,0 - 17 years,Female,<NA>,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN
4,2021-08-01,OH,LORAIN,0 - 17 years,Male,<NA>,Probable Case,Missing,Missing,Missing,Unknown,NaN

In [157]:
tableau_df.dropna(subset=['age_group', 'sex', 'race'], inplace = True)

display(tableau_df.head(10))
print(len(tableau_df))

,case_month,res_state,res_county,age_group,sex,race,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-11-01,HI,HONOLULU,50 to 64 years,Female,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
2,2021-08-01,ID,ADA,18 to 49 years,Male,White,Laboratory-confirmed case,Unknown,No,Missing,No,NaN
6,2021-01-01,SC,SPARTANBURG,18 to 49 years,Female,Black,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
7,2022-05-01,MD,ANNE ARUNDEL,18 to 49 years,Male,White,Probable Case,Symptomatic,Missing,Missing,No,NaN
8,2022-03-01,FL,MIAMI-DADE,50 to 64 years,Male,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
10,2022-05-01,NJ,UNION,50 to 64 years,Male,Asian,Laboratory-confirmed case,Symptomatic,Yes,Missing,No,NaN
11,2023-02-01,MI,INGHAM,18 to 49 years,Female,Black,Laboratory-confirmed case,Missing,Missing,Missing,Unknown,NaN
12,2022-07-01,FL,ST. LUCIE,18 to 49 years,Female,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
13,2022-01-01,MN,DAKOTA,50 to 64 years,Female,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,No,Yes
14,2021-10-01,MI,KALAMAZOO,18 to 49 years,Male,White,Probable Case,Missing,Missing,Missing,Unknown,NaN

7618226

In [159]:
import numpy as np

tableau_df[['age_group', 'sex', 'race']] = tableau_df[['age_group', 'sex', 'race']].replace('NA', np.nan)

In [160]:
tableau_df.dropna(subset=['age_group', 'sex', 'race'], inplace = True)

In [161]:
tableau_columns = ['age_group', 'sex', 'race']
for col in tableau_columns: 
    print(col, tableau_df[col].unique())

age_group ['50 to 64 years' '18 to 49 years' '65+ years' '0 - 17 years']
sex ['Female' 'Male' 'Other']
race ['White' 'Black' 'Asian' 'Multiple/Other' 'American Indian/Alaska Native'
 'Native Hawaiian/Other Pacific Islander']

In [162]:
display(tableau_df.head(10))
print(len(tableau_df))

,case_month,res_state,res_county,age_group,sex,race,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-11-01,HI,HONOLULU,50 to 64 years,Female,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
2,2021-08-01,ID,ADA,18 to 49 years,Male,White,Laboratory-confirmed case,Unknown,No,Missing,No,NaN
6,2021-01-01,SC,SPARTANBURG,18 to 49 years,Female,Black,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
7,2022-05-01,MD,ANNE ARUNDEL,18 to 49 years,Male,White,Probable Case,Symptomatic,Missing,Missing,No,NaN
8,2022-03-01,FL,MIAMI-DADE,50 to 64 years,Male,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
10,2022-05-01,NJ,UNION,50 to 64 years,Male,Asian,Laboratory-confirmed case,Symptomatic,Yes,Missing,No,NaN
11,2023-02-01,MI,INGHAM,18 to 49 years,Female,Black,Laboratory-confirmed case,Missing,Missing,Missing,Unknown,NaN
12,2022-07-01,FL,ST. LUCIE,18 to 49 years,Female,White,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
13,2022-01-01,MN,DAKOTA,50 to 64 years,Female,White,Laboratory-confirmed case,Symptomatic,Missing,Missing,No,Yes
14,2021-10-01,MI,KALAMAZOO,18 to 49 years,Male,White,Probable Case,Missing,Missing,Missing,Unknown,NaN

6389751

In [ ]:
tableau_df.to_csv('resources/demographic_analysis/tableau.csv', index = False)

# Cleaned DataFrame for Machine Learning

In [52]:
clean_df = df.copy()
clean_df = clean_df.drop(['case_month', 'res_state', 'res_county', 'hosp_yn'], axis=1)
clean_df.head(10)

,age_group,sex,race,current_status,symptom_status,icu_yn,death_yn,underlying_conditions_yn
0,50 to 64 years,Female,White,Laboratory-confirmed case,Missing,Missing,Missing,NaN
1,18 to 49 years,Female,Unknown,Laboratory-confirmed case,Symptomatic,Missing,No,NaN
2,18 to 49 years,Male,White,Laboratory-confirmed case,Unknown,Missing,No,NaN
3,0 - 17 years,Female,Unknown,Laboratory-confirmed case,Unknown,Missing,Missing,NaN
4,0 - 17 years,Male,Unknown,Probable Case,Missing,Missing,Unknown,NaN
5,50 to 64 years,Male,Unknown,Laboratory-confirmed case,Missing,Missing,Missing,NaN
6,18 to 49 years,Female,Black,Laboratory-confirmed case,Missing,Missing,Missing,NaN
7,18 to 49 years,Male,White,Probable Case,Symptomatic,Missing,No,NaN
8,50 to 64 years,Male,White,Laboratory-confirmed case,Missing,Missing,Missing,NaN
9,18 to 49 years,Female,Unknown,Probable Case,Missing,Missing,Unknown,NaN

In [53]:
for col in clean_df.columns: 
    print(col, df[col].unique())

age_group ['50 to 64 years' '18 to 49 years' '0 - 17 years' '65+ years' 'Missing'
 'NA']
sex ['Female' 'Male' 'Unknown' 'NA' 'Missing' 'Other']
race ['White' 'Unknown' 'Black' 'Asian' 'Missing' 'NA' 'Multiple/Other'
 'American Indian/Alaska Native' 'Native Hawaiian/Other Pacific Islander']
current_status ['Laboratory-confirmed case' 'Probable Case']
symptom_status ['Missing' 'Symptomatic' 'Unknown' 'Asymptomatic']
icu_yn ['Missing' 'Unknown' 'No' 'Yes']
death_yn ['Missing' 'No' 'Unknown' 'NA' 'Yes']
underlying_conditions_yn [nan 'Yes' 'No']

In [54]:
clean_df['age_group'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
clean_df['sex'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
clean_df['race'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
clean_df['symptom_status'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
clean_df['icu_yn'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)
clean_df['death_yn'].replace({'Unknown': pd.NA, 'Missing': pd.NA}, inplace=True)

clean_df = clean_df[clean_df[['age_group', 'sex', 'race', 'symptom_status', 'icu_yn', 'death_yn']] != 'NA']
clean_df.dropna(subset=['age_group', 'sex', 'race', 'symptom_status', 'icu_yn', 'death_yn'], inplace = True)
clean_df.head()

,age_group,sex,race,current_status,symptom_status,icu_yn,death_yn,underlying_conditions_yn
19,0 - 17 years,Male,Asian,NaN,Symptomatic,No,No,NaN
34,18 to 49 years,Female,White,NaN,Symptomatic,No,No,NaN
91,0 - 17 years,Male,White,NaN,Symptomatic,No,No,NaN
109,18 to 49 years,Female,White,NaN,Symptomatic,No,No,NaN
169,18 to 49 years,Female,White,NaN,Symptomatic,No,No,NaN

In [55]:
for col in clean_df.columns: 
    print(col, clean_df[col].unique())

age_group ['0 - 17 years' '18 to 49 years' '65+ years' '50 to 64 years']
sex ['Male' 'Female']
race ['Asian' 'White' 'Black' 'Multiple/Other'
 'Native Hawaiian/Other Pacific Islander' 'American Indian/Alaska Native']
current_status [nan]
symptom_status ['Symptomatic' 'Asymptomatic']
icu_yn ['No' 'Yes']
death_yn ['No' 'Yes']
underlying_conditions_yn [nan]

In [68]:
new_clean_df = clean_df.drop(['current_status', 'underlying_conditions_yn'], axis=1)
new_clean_df['death_yn'] = new_clean_df['death_yn'].replace({'Yes': 1, 'No': 0})
new_clean_df.head()

          age_group     sex   race symptom_status icu_yn  death_yn
19     0 - 17 years    Male  Asian    Symptomatic     No         0
34   18 to 49 years  Female  White    Symptomatic     No         0
91     0 - 17 years    Male  White    Symptomatic     No         0
109  18 to 49 years  Female  White    Symptomatic     No         0
169  18 to 49 years  Female  White    Symptomatic     No         0

In [69]:
new_clean_df.dtypes

age_group         object
sex               object
race              object
symptom_status    object
icu_yn            object
death_yn           int64
dtype: object

In [71]:
encoded_df = pd.get_dummies(new_clean_df, columns = ['age_group', 'sex', 'race', 'symptom_status', 'icu_yn'])
encoded_df.head(25)

,death_yn,age_group_0 - 17 years,age_group_18 to 49 years,age_group_50 to 64 years,age_group_65+ years,sex_Female,sex_Male,race_American Indian/Alaska Native,race_Asian,race_Black,race_Multiple/Other,race_Native Hawaiian/Other Pacific Islander,race_White,symptom_status_Asymptomatic,symptom_status_Symptomatic,icu_yn_No,icu_yn_Yes
19,0,1,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0
34,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
91,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1,1,0
109,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
169,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
185,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,1,0
211,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
266,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
309,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
366,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1,1,0
444,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
486,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
522,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,1,0
540,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
580,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
585,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
608,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1,1,0
610,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,1,0
632,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,1,0
645,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1,1,0
662,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
706,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,1,0
759,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
816,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0
858,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0

In [72]:
encoded_df['death_yn'].unique()

array([0, 1], dtype=int64)

In [73]:
# Set up for machine learning mortality model
y = encoded_df['death_yn']
X = encoded_df.drop(columns= 'death_yn')

# Logistic Regression Attempt

In [88]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=1, stratify=y)

In [111]:
# Initiate similar to Module #18

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
   max_iter=200,
   random_state=1)

In [112]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=200, random_state=1)

In [113]:
y_pred = classifier.predict(X_test)

In [114]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(f"Accuracy Score: {accuracy_score(y_test, y_pred)}")
print("\nClassification Report: \n")
report = classification_report(y_test, y_pred)
print(report)

Accuracy Score: 0.9722793590050227

Classification Report:

              precision    recall  f1-score   support

           0       0.98      0.99      0.99     40438
           1       0.61      0.42      0.50      1372

    accuracy                           0.97     41810
   macro avg       0.80      0.71      0.74     41810
weighted avg       0.97      0.97      0.97     41810

In [115]:
cm_log = confusion_matrix(y_test, y_pred)
cm_log_df = pd.DataFrame(
    cm_log, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_log_df

          Predicted 0  Predicted 1
Actual 0        40071          367
Actual 1          792          580

# SVC

In [116]:
X_train_SVC, X_test_SVC, y_train_SVC, y_test_SVC = train_test_split(X,
   y,  random_state=1, stratify=y)
X_train_SVC.shape

(125428, 16)

In [117]:
from sklearn.svm import SVC
model = SVC(kernel='linear')

In [118]:
model.fit(X_train_SVC, y_train_SVC)

SVC(kernel='linear')

In [119]:
y_pred_SVC = model.predict(X_test_SVC)

In [120]:
cm_SVC = confusion_matrix(y_test_SVC, y_pred_SVC)
cm_SVC_df = pd.DataFrame(
    cm_SVC, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_SVC_df

          Predicted 0  Predicted 1
Actual 0        40071          367
Actual 1          792          580

In [121]:
print(f"Accuracy Score: {accuracy_score(y_test_SVC, y_pred_SVC)}")
print(classification_report(y_test_SVC, y_pred_SVC))

Accuracy Score: 0.9722793590050227
              precision    recall  f1-score   support

           0       0.98      0.99      0.99     40438
           1       0.61      0.42      0.50      1372

    accuracy                           0.97     41810
   macro avg       0.80      0.71      0.74     41810
weighted avg       0.97      0.97      0.97     41810

# Random Forest

In [122]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

In [123]:
X_train_RF, X_test_RF, y_train_RF, y_test_RF = train_test_split(X, y, random_state=1)

In [124]:
scaler = StandardScaler()
X_scaler = scaler.fit(X_train_RF)

X_train_scaled_RF = X_scaler.transform(X_train_RF)
X_test_scaled_RF = X_scaler.transform(X_test_RF)

In [125]:
rf_model = RandomForestClassifier(n_estimators=128, random_state=1) 
rf_model = rf_model.fit(X_train_scaled_RF, y_train_RF)

In [134]:
predictions_RF = rf_model.predict(X_test_scaled_RF)
cm = confusion_matrix(y_test_RF, predictions_RF)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

In [127]:
acc_score_RF = accuracy_score(y_test_RF, predictions_RF)

In [133]:
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score_RF}")
print("Classification Report")
print(classification_report(y_test_RF, predictions_RF))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0        40057          321
Actual 1          845          587

Accuracy Score : 0.9721119349437933
Classification Report
              precision    recall  f1-score   support

           0       0.98      0.99      0.99     40378
           1       0.65      0.41      0.50      1432

    accuracy                           0.97     41810
   macro avg       0.81      0.70      0.74     41810
weighted avg       0.97      0.97      0.97     41810

# Random Oversampler

In [130]:
from collections import Counter
X_train_ROS, X_test_ROS, y_train_ROS, y_test_ROS = train_test_split(X, y, random_state=1)
Counter(y_train)

Counter({0: 121314, 1: 4114})

In [132]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)

X_resampled_ROS, y_resampled_ROS = ros.fit_resample(X_train_ROS, y_train_ROS)

In [136]:
model_ROS = LogisticRegression(solver='lbfgs', max_iter=500, random_state=1)
model_ROS.fit(X_resampled_ROS, y_resampled_ROS)

LogisticRegression(max_iter=500, random_state=1)

In [137]:
y_pred_ROS = model.predict(X_test_ROS)

cm_ROS = confusion_matrix(y_test_ROS, y_pred_ROS)
cm_df_ROS = pd.DataFrame(
    cm_ROS, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

In [141]:
from imblearn.metrics import classification_report_imbalanced
from sklearn.metrics import balanced_accuracy_score

acc_score_ROS= balanced_accuracy_score(y_test_RF, y_pred_ROS)

print("Confusion Matrix")
display(cm_df_ROS)
print(f"Accuracy Score : {acc_score_ROS}")
print("Classification Report")
print(classification_report_imbalanced(y_test_RF, y_pred_ROS))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0        40050          328
Actual 1          842          590

Accuracy Score : 0.701943968879563
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

          0       0.98      0.99      0.41      0.99      0.64      0.43     40378
          1       0.64      0.41      0.99      0.50      0.64      0.38      1432

avg / total       0.97      0.97      0.43      0.97      0.64      0.43     41810